DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x133b470b0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 47, in data_received
    message = json.loads(data.decode())
                         ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 1: invalid start byte
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x133b474a0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 50, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 57, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in on_login
    request_message = Server_Private_Key.decrypt(message)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RSAPrivateKey.decrypt() missing 1 required positional argument: 'padding'
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x10d5bf5c0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 50, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 57, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 65, in on_login
    request_message = Server_Private_Key.decrypt(message)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RSAPrivateKey.decrypt() missing 1 required positional argument: 'padding'
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x13593f830>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 55, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 62, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 76, in on_login
    password_hash = DB.find_one({"username": username})["hashed_password"]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x12ae7ec90>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, argon2_params.encode("ascii"))
                                                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'encode'
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x13327aba0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, argon2_params.encode("ascii"))
                                                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'encode'
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x12eef2cf0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, json.dumps(argon2_params).encode('ascii'))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Type is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x1089f2f30>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, json.dumps(argon2_params).encode('ascii'))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Type is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x110282ea0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, json.dumps(argon2_params).encode('ascii'))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Type is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x10a57ef30>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, json.dumps(argon2_params))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Type is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x1145f6bd0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 100, in on_login
    "payload": json.dumps(payload).encode()}
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x11108a780>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 94, in on_login
    argon2_params_signature = sign_data(Server_Private_Key, json.dumps(argon2_params))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/util/crypto.py", line 68, in sign_data
    return private_key.sign(
           ^^^^^^^^^^^^^^^^^
TypeError: argument 'data': from_buffer() cannot return the address of a unicode object
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x13017acf0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 100, in on_login
    "payload": json.dumps(payload).encode()}
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x113abeb70>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 90, in on_login
    argon2_params = fetch_argon2_params(password_hash)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/util/crypto.py", line 163, in fetch_argon2_params
    salt = extract_salt_from_hash(argon2_hash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/util/crypto.py", line 193, in extract_salt_from_hash
    return base64.b64decode(salt_base64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x1139f5a00>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 90, in on_login
    argon2_params = fetch_argon2_params(password_hash)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/util/crypto.py", line 163, in fetch_argon2_params
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/util/crypto.py", line 193, in extract_salt_from_hash
    else:
          
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x1073235c0>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 86, in on_login
    user_doc = DB.find_one({"username": username})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/collection.py", line 1506, in find_one
    for result in cursor.limit(-1):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/cursor.py", line 1264, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-z71kwpr-shard-00-02.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-z71kwpr-shard-00-01.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-z71kwpr-shard-00-00.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66149dda404f3f29160e2650, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-z71kwpr-shard-00-00.5lef1kv.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-z71kwpr-shard-00-00.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-z71kwpr-shard-00-01.5lef1kv.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-z71kwpr-shard-00-01.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-z71kwpr-shard-00-02.5lef1kv.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-z71kwpr-shard-00-02.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x1072f8e00>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 64, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 71, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 86, in on_login
    user_doc = DB.find_one({"username": username})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/collection.py", line 1506, in find_one
    for result in cursor.limit(-1):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/cursor.py", line 1264, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1823, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    self._topology._check_implicit_session_support()
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/topology.py", line 573, in _check_implicit_session_support
    self._check_session_support()
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/topology.py", line 589, in _check_session_support
    self._select_servers_loop(
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/site-packages/pymongo/topology.py", line 259, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-z71kwpr-shard-00-02.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-z71kwpr-shard-00-01.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-z71kwpr-shard-00-00.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66149dda404f3f29160e2650, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-z71kwpr-shard-00-00.5lef1kv.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-z71kwpr-shard-00-00.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-z71kwpr-shard-00-01.5lef1kv.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-z71kwpr-shard-00-01.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-z71kwpr-shard-00-02.5lef1kv.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-z71kwpr-shard-00-02.5lef1kv.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x12e6f3fe0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 72, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 80, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 143, in on_login
    "payload": json.dumps(payload)  # This stays as a string
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x1338ebf50>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 72, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 80, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 144, in on_login
    "payload": json.dumps(payload)  # This stays as a string
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x10c9174d0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 72, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 80, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 143, in on_login
    "payload": json.dumps(payload)  # This stays as a string
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x12f5350d0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 74, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 82, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 173, in on_login
    cipher_text = base64.b64decode(chal_resp_payload["ciphertext"])
                                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.TCPAuthServerProtocol object at 0x12e264b00>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/lemon2ee/.pyenv/versions/3.12.1/lib/python3.12/asyncio/selector_events.py", line 1023, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 74, in data_received
    self.process_message(message, addr)
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 82, in process_message
    return self.on_login(message, addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lemon2ee/Documents/Github/CY4740_Project/src/server.py", line 174, in on_login
    cipher_text = base64.b64decode(chal_resp_payload["ciphertext"])
                                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
